apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: 'true'
  users.anonymous.enabled: 'false'

  configManagementPlugins: |
    - name: apisero-argocd-vault
      generate:
        command: [argocd-vault-plugin]
        args: 
          - generate
          - ./ 

    - name: apisero-argocd-vault-helm
      init:
        command: [sh, -c]
        args:
          - |
            helm repo add bitnami https://charts.bitnami.com/bitnami
      generate:
        command: [sh, -c]
        args: 
          - |
            helm template $ARGOCD_APP_NAME ${helm_args} -n $ARGOCD_APP_NAMESPACE . |\
            argocd-vault-plugin generate -
