kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "secret/data/my-nginx"
type: Opaque
stringData:
  sample-secret: <password>
data: 
  - name: AVP_TYPE
    value: vault
  - name: VAULT_ADDR
    value: http://a08aa61a3b95c49c896c10ba60820e20-339658178.us-east-1.elb.amazonaws.com:8200
  - name: AVP_AUTH_TYPE
    value: token
  - name: VAULT_TOKEN
    value: root
