apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-manifests
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: 'https://github.com/jkayani/avp-demo-kubecon-2021'
    targetRevision: HEAD
    path: apps/helm/complex-redis/extra-manifests
    plugin:
      name: argocd-vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
