kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "secrets/secret/avp/dynatrace"
type: Opaque
stringData:
  password: <password> 
data:
  VAULT_ADDR: http://localhost:8200/ui
  VAULT_TOKEN: hvs.qqT9W7TezZFBIcCZBJHorus4
  AVP_TYPE: vault
  AVP_AUTH_TYPE: token
