kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
data:
  AVP_AUTH_TYPE: oidc
  AVP_ROLE_ID: ${{secrets.AVP_ROLE_ID}}
  AVP_SECRET_ID: ${{secrets.AVP_SECRET_ID}}
  AVP_TYPE: vault
  VAULT_ADDR: "https://vault.metronet.cloud/ui/"
